   name: SketchSite
   options:
     bundleIdPrefix: com.tylerschmidt
   schemes:
     SketchSite:
       build:
         targets:
           SketchSite: all
       run:
         config: Debug
       test:
         config: Debug
         targets:
           - SketchSiteTests
           - SketchSiteUITests
       archive:
         config: Release
   targets:
     SketchSite:
       type: application
       platform: iOS
       sources:
         - Views
         - Utilities
         - Services
         - Assets.xcassets
         - SketchSiteApp.swift
         - DiagnosticsRunner.swift
         - PrivacyInfo.xcprivacy
       info:
         path: Info.plist
         properties:
           UILaunchScreen:
             UIColorName: ""
             UIImageName: ""
           UISupportedInterfaceOrientations:
             - UIInterfaceOrientationPortrait
             - UIInterfaceOrientationPortraitUpsideDown
             - UIInterfaceOrientationLandscapeLeft
             - UIInterfaceOrientationLandscapeRight
           UIRequiresFullScreen: true
           UIStatusBarHidden: false
           UIViewControllerBasedStatusBarAppearance: false
           LSRequiresIPhoneOS: true
           UIApplicationSceneManifest:
             UIApplicationSupportsMultipleScenes: false
             UISceneConfigurations:
               UIWindowSceneSessionRoleApplication:
                 - UISceneConfigurationName: "Default Configuration"
                   UISceneDelegateClassName: "$(PRODUCT_MODULE_NAME).SceneDelegate"
           NSCameraUsageDescription: "SketchSite uses the camera to analyze existing UI screenshots and mockups for component detection."
           NSPhotoLibraryUsageDescription: "SketchSite accesses your photo library to import images for UI analysis and component detection."
           CFBundleDisplayName: "SketchSite"
           LSApplicationCategoryType: "public.app-category.productivity"
       settings:
         base:
           PRODUCT_BUNDLE_IDENTIFIER: com.tylerschmidt.SketchSite
           DEVELOPMENT_TEAM: C8XAFC8DSU
           CODE_SIGN_STYLE: Automatic
           CODE_SIGN_IDENTITY: "Apple Development"
           IPHONEOS_DEPLOYMENT_TARGET: 18.0
           TARGETED_DEVICE_FAMILY: "1,2"
           SWIFT_VERSION: 5.0
           ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
           MARKETING_VERSION: "1.0.0"
           CURRENT_PROJECT_VERSION: "1"
         release:
           CODE_SIGN_IDENTITY: "iPhone Distribution"
           SWIFT_OPTIMIZATION_LEVEL: "-O"
           SWIFT_COMPILATION_MODE: wholemodule
     SketchSiteTests:
       type: bundle.unit-test
       platform: iOS
       sources: [SketchSiteTests]
       dependencies:
         - target: SketchSite
       settings:
         base:
           PRODUCT_BUNDLE_IDENTIFIER: com.tylerschmidt.SketchSiteTests
           DEVELOPMENT_TEAM: C8XAFC8DSU
     SketchSiteUITests:
       type: bundle.ui-testing
       platform: iOS
       sources: [SketchSiteUITests]
       dependencies:
         - target: SketchSite
       settings:
         base:
           PRODUCT_BUNDLE_IDENTIFIER: com.tylerschmidt.SketchSiteUITests
           DEVELOPMENT_TEAM: C8XAFC8DSU
