   name: SketchSite
   options:
     bundleIdPrefix: com.tylerschmidt
   targets:
     SketchSite:
       type: application
       platform: iOS
       sources:
         - Views
         - Utilities
         - Services
         - SketchSiteApp.swift
         - DiagnosticsRunner.swift
       info:
         path: Info.plist
       settings:
         base:
           PRODUCT_BUNDLE_IDENTIFIER: com.tylerschmidt.SketchSite
           DEVELOPMENT_TEAM: C8XAFC8DSU
           CODE_SIGN_STYLE: Automatic
           CODE_SIGN_IDENTITY: "Apple Development"
           IPHONEOS_DEPLOYMENT_TARGET: 18.0
           TARGETED_DEVICE_FAMILY: "1,2"
           SWIFT_VERSION: 5.0
     SketchSiteTests:
       type: bundle.unit-test
       platform: iOS
       sources: [SketchSiteTests]
       dependencies:
         - target: SketchSite
       settings:
         base:
           PRODUCT_BUNDLE_IDENTIFIER: com.tylerschmidt.SketchSiteTests
           DEVELOPMENT_TEAM: C8XAFC8DSU
     SketchSiteUITests:
       type: bundle.ui-testing
       platform: iOS
       sources: [SketchSiteUITests]
       dependencies:
         - target: SketchSite
       settings:
         base:
           PRODUCT_BUNDLE_IDENTIFIER: com.tylerschmidt.SketchSiteUITests
           DEVELOPMENT_TEAM: C8XAFC8DSU
